# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c5b6bc64c36fa29d5a1dabf870966a3d95d2191549727d652fb4be04ccbca870d399e5481d6e6d91027b6d61615f5eb6fa67809b007c956b2d3cce06247f794

test:
  secret_key_base: dd44ededf64307c5ed8946a2e774f5fe27fdea8ba01feac1c0a0531bba59f9f22378fcccda4a74b5d2a691df58c9a4adeae580035d82bd7a8ff9c8515944668e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
